version: '3.2'
services:
  api:
    build: ../didactic-bassoon
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - secrets.docker
    depends_on:
      - db
  db:
    image: "postgres"
    restart: unless-stopped
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/database-data:/var/lib/postgresql/data/
